-- Extreme vocals path (metal, death metal, black metal, thrash). These use the
-- vocal_drill_picker generator: the big label is a vowel, syllable or cue, and
-- the detail line comes from `cues` (per item) or `patterns` (random).
-- `tutorial_query` is what the tutorial picker searches YouTube for.

INSERT INTO skills (id, path, category, name, description, generator_type, config, mastery_reps, sort_order) VALUES

-- Foundations
('vocals.breath_support', 'vocals', 'Foundations', 'Breath Support',
 'Every extreme technique runs on steady, supported air. Belly moves, shoulders stay still, and the throat never does the pushing.',
 'vocal_drill_picker',
 '{"pool": ["SSS","HA","4-4-8","PANT","SHH"], "default_selected": ["SSS","HA","4-4-8"], "pool_label": "Exercises", "tempo_label": "Cue tempo",
   "cues": {"SSS": "One slow, even hiss on a single breath. Keep the belly out as long as you can",
            "HA": "Short staccato HA pulses from the belly, one per beat",
            "4-4-8": "Inhale for 4 beats, hold for 4, release on a hiss for 8",
            "PANT": "Quick silent pants to feel the diaphragm kick in",
            "SHH": "Pulse SHH on the beat, then sustain the last one"},
   "tutorial_query": "breath support for screaming vocals tutorial",
   "default_bpm": 60, "min_bpm": 40, "max_bpm": 120, "default_sets": 3, "default_reps": 6}'::jsonb,
 120, 10),

('vocals.warmups', 'vocals', 'Foundations', 'Warm-up & Cool-down',
 'Five minutes before any screaming and a few after. Gentle, clean-voice work that gets the cords moving without strain.',
 'vocal_drill_picker',
 '{"pool": ["TRILL","SIREN","STRAW","HUM","YAWN"], "default_selected": ["TRILL","SIREN","STRAW","HUM","YAWN"], "pool_label": "Exercises", "tempo_label": "Cue tempo",
   "cues": {"TRILL": "Lip trill sliding from low to high and back",
            "SIREN": "NG siren through your whole range, quiet and smooth",
            "STRAW": "Hum through a straw, sliding up and down",
            "HUM": "Gentle descending hum, lips loosely closed",
            "YAWN": "Yawn-sigh from high to low to open the throat"},
   "tutorial_query": "warm up for screaming vocals metal",
   "default_bpm": 50, "min_bpm": 30, "max_bpm": 100, "default_sets": 2, "default_reps": 5}'::jsonb,
 100, 20),

-- Core techniques
('vocals.fry_control', 'vocals', 'Core Techniques', 'Vocal Fry Control',
 'The quiet crackle at the bottom of your voice is the root of most fry screams. Learn to hold it steady with almost no effort.',
 'vocal_drill_picker',
 '{"pool": ["AH","EH","EE","OH","OO"], "default_selected": ["AH","EH","OH"], "pool_label": "Vowels", "tempo_label": "Cue tempo",
   "patterns": ["Quiet, steady fry for 4 beats. No push from the throat",
                "Fry, then add a little more air without getting louder",
                "Fry and slide slowly up in pitch, then back down",
                "Start and stop the fry cleanly on each beat"],
   "tutorial_query": "vocal fry scream tutorial for beginners",
   "default_bpm": 60, "min_bpm": 40, "max_bpm": 120, "default_sets": 3, "default_reps": 8}'::jsonb,
 160, 30),

('vocals.fry_screams', 'vocals', 'Core Techniques', 'Fry Screams (Highs)',
 'Build fry into a full high scream with support and an open throat. Short bursts first, and stop the moment anything scratches.',
 'vocal_drill_picker',
 '{"pool": ["EE","EH","AY","AH"], "default_selected": ["EE","EH","AY"], "pool_label": "Vowels", "tempo_label": "Cue tempo",
   "patterns": ["Fry into a short scream for 2 beats, then rest",
                "Grow from fry to full distortion over 4 beats",
                "Two short bursts with a breath between them",
                "Hold the scream at medium volume for 4 beats"],
   "tutorial_query": "fry scream highs tutorial",
   "default_bpm": 60, "min_bpm": 40, "max_bpm": 130, "default_sets": 3, "default_reps": 6}'::jsonb,
 180, 40),

('vocals.false_cord', 'vocals', 'Core Techniques', 'False Cord Mids',
 'The big, roaring mid scream used across metal and metalcore. Retract, let the false folds rattle on air, and keep the true cords relaxed.',
 'vocal_drill_picker',
 '{"pool": ["AH","EH","OH","UH"], "default_selected": ["AH","EH","UH"], "pool_label": "Vowels", "tempo_label": "Cue tempo",
   "patterns": ["Silent laugh to retract, then add air for 2 beats",
                "Start from a light cough position and sustain on air",
                "Short false cord bursts, one per beat",
                "Sustain for 4 beats at an easy volume. Stop if it scratches"],
   "tutorial_query": "false cord scream tutorial",
   "default_bpm": 60, "min_bpm": 40, "max_bpm": 140, "default_sets": 3, "default_reps": 6}'::jsonb,
 200, 50),

('vocals.lows', 'vocals', 'Core Techniques', 'Fry Lows & Gutturals',
 'Deep, dark lows built from fry with a lowered larynx and rounded lips. The foundation of death metal vocals.',
 'vocal_drill_picker',
 '{"pool": ["OO","OH","UH","EUGH"], "default_selected": ["OO","OH","UH"], "pool_label": "Vowels", "tempo_label": "Cue tempo",
   "patterns": ["Fry, drop the larynx and round the lips for a darker low",
                "Sustain a low for 4 beats on steady air",
                "Short guttural bursts, one per beat",
                "Move from OO to AH without losing the depth"],
   "tutorial_query": "fry lows guttural vocals tutorial death metal",
   "default_bpm": 60, "min_bpm": 40, "max_bpm": 140, "default_sets": 3, "default_reps": 6}'::jsonb,
 200, 60),

-- Styles
('vocals.death_growls', 'vocals', 'Styles', 'Death Metal Growls',
 'Low, cavernous growls locked to the riff. Keep the vowels dark and let the words land on the beat.',
 'vocal_drill_picker',
 '{"pool": ["BLEGH","RAH","UGH","GRAH","DEATH"], "default_selected": ["BLEGH","RAH","UGH"], "pool_label": "Syllables", "tempo_label": "Cue tempo",
   "patterns": ["One growl on the beat, clipped short",
                "Sustain the growl for a full bar",
                "Two growls per beat, like a blast section",
                "Growl the syllable, then drop even lower on the tail"],
   "tutorial_query": "death metal growl tutorial",
   "default_bpm": 90, "min_bpm": 50, "max_bpm": 200, "default_sets": 3, "default_reps": 8}'::jsonb,
 200, 70),

('vocals.black_shrieks', 'vocals', 'Styles', 'Black Metal Shrieks',
 'Thin, airy, hissing highs with a cold edge. The rasp comes from air and placement, never from squeezing the throat.',
 'vocal_drill_picker',
 '{"pool": ["EE","AY","EH","KHH"], "default_selected": ["EE","AY","EH"], "pool_label": "Vowels", "tempo_label": "Cue tempo",
   "patterns": ["Airy high fry with a hissing edge for 4 beats",
                "Sustain the shriek and let it fade slowly",
                "Short shrieks on the offbeats",
                "Keep it quiet and thin before adding volume"],
   "tutorial_query": "black metal vocals tutorial shriek",
   "default_bpm": 80, "min_bpm": 50, "max_bpm": 220, "default_sets": 3, "default_reps": 6}'::jsonb,
 200, 80),

('vocals.thrash_shouts', 'vocals', 'Styles', 'Thrash Shouts',
 'Barked, gritty shouts that sit right on the riff. Think gang vocals and punchy mid rasp rather than long screams.',
 'vocal_drill_picker',
 '{"pool": ["HEY","GO","NO","YEAH","DIE"], "default_selected": ["HEY","GO","NO"], "pool_label": "Syllables", "tempo_label": "Cue tempo",
   "patterns": ["One barked shout on the beat, clipped short",
                "Two quick shouts back to back",
                "Gritty mid on the vowel for 2 beats",
                "Gang-vocal style: shout it with the snare"],
   "tutorial_query": "thrash metal vocals tutorial",
   "default_bpm": 120, "min_bpm": 70, "max_bpm": 220, "default_sets": 3, "default_reps": 8}'::jsonb,
 180, 90),

('vocals.pitched_grit', 'vocals', 'Styles', 'Pitched Grit',
 'Heavy and classic metal singing with distortion layered on a real note. Keep the pitch clean underneath the grit.',
 'vocal_drill_picker',
 '{"pool": ["AH","EH","OH","AY"], "default_selected": ["AH","EH","OH"], "pool_label": "Vowels", "tempo_label": "Cue tempo",
   "patterns": ["Sing a comfortable note, then add a little grit on top",
                "Slide between two notes keeping the grit steady",
                "Clean for 2 beats, gritty for 2 beats",
                "Belt a short phrase with grit on the last note"],
   "tutorial_query": "how to add grit to your singing voice metal",
   "default_bpm": 70, "min_bpm": 40, "max_bpm": 160, "default_sets": 3, "default_reps": 6}'::jsonb,
 200, 100),

-- Application
('vocals.rhythmic_phrasing', 'vocals', 'Application', 'Rhythmic Phrasing',
 'Put screams on the grid. Pick your technique, then deliver it in each rhythm against the click.',
 'vocal_drill_picker',
 '{"pool": ["1/4","1/8","TRIP","GALLOP","OFF"], "default_selected": ["1/4","1/8","GALLOP"], "pool_label": "Rhythms", "tempo_label": "Click tempo",
   "cues": {"1/4": "One syllable on every beat",
            "1/8": "Two syllables per beat",
            "TRIP": "Three syllables per beat",
            "GALLOP": "Thrash gallop: da-da-DUH on each beat",
            "OFF": "Land every syllable on the offbeat"},
   "tutorial_query": "metal vocal rhythm phrasing tutorial",
   "default_bpm": 100, "min_bpm": 60, "max_bpm": 220, "default_sets": 3, "default_reps": 8}'::jsonb,
 200, 110);

-- Cached tutorial picks per skill. YouTube's API quota is small, so the app
-- searches once and reuses the result until it's stale or the user refreshes.
CREATE TABLE skill_tutorials (
  skill_id TEXT PRIMARY KEY REFERENCES skills(id) ON DELETE CASCADE,
  query TEXT NOT NULL,
  videos JSONB NOT NULL,
  fetched_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
