-- Genre subpaths for Rhythm, Lead and Bass, the way Extreme Vocals has its
-- death, black and thrash styles. Each genre is its own category, so it shows as
-- a section on the skill list, and sorts after the path's core skills (100+).
-- Chord skills use random_chord_picker with `patterns`, which puts an
-- instruction under each chord; everything else uses cue_picker. Every skill
-- has a tutorial_query. Counting uses 1 e & a, so "the & of 4" is the offbeat.

INSERT INTO skills (id, path, category, name, description, generator_type, config, mastery_reps, sort_order) VALUES

-- Rhythm Guitar: Blues
('rhythm.blues_shuffle', 'rhythm', 'Blues', 'Blues Shuffle',
 'The boogie shuffle under a thousand blues and early rock songs. Swing the eighths long-short and keep the picking hand moving.',
 'cue_picker',
 '{"pool": ["E","A","B","D","G","C"], "default_selected": ["E","A","B"], "pool_label": "Roots", "tempo_label": "Shuffle tempo",
   "patterns": ["Root and 5th, then root and 6th, back and forth in swung eighths",
                "Stretch it: 5th, 6th, b7, 6th across the bar",
                "Palm-mute lightly and accent beats 2 and 4",
                "Two bars on this root, then change without a gap"],
   "tutorial_query": "blues shuffle rhythm guitar lesson",
   "default_bpm": 80, "min_bpm": 50, "max_bpm": 160, "default_sets": 3, "default_reps": 8}'::jsonb,
 200, 100),

('rhythm.blues_twelve_bar', 'rhythm', 'Blues', '12-Bar Blues Changes',
 'The form itself. Play each version once through in E or A, counting bars out loud until the changes land without thinking.',
 'cue_picker',
 '{"pool": ["SLOW","QUICK","STOP","MINOR","TURN"], "default_selected": ["SLOW","QUICK"], "pool_label": "Forms", "tempo_label": "Click tempo",
   "cues": {"SLOW": "I I I I · IV IV I I · V IV I V",
            "QUICK": "I IV I I · IV IV I I · V IV I V. The quick change comes in bar 2",
            "STOP": "Stop-time: hit I on beat 1 of bars 1 to 4 and let it ring, then play bars 5 to 12",
            "MINOR": "i i i i · iv iv i i · bVI V i V",
            "TURN": "Bars 11 and 12 only, I then V, four times through"},
   "tutorial_query": "12 bar blues rhythm guitar lesson",
   "default_bpm": 80, "min_bpm": 50, "max_bpm": 150, "default_sets": 3, "default_reps": 4}'::jsonb,
 120, 110),

-- Rhythm Guitar: Rock
('rhythm.rock_eighths', 'rhythm', 'Rock', 'Driving Eighths',
 'The engine of rock rhythm: steady eighth notes on power chords, shaped with palm muting and accents.',
 'cue_picker',
 '{"pool": ["MUTED","OPEN","ACCENT","PUSH","STAB"], "default_selected": ["MUTED","OPEN","ACCENT"], "pool_label": "Patterns", "tempo_label": "Click tempo",
   "cues": {"MUTED": "Palm-muted eighths on one power chord, all downstrokes",
            "OPEN": "The same eighths with the mute lifted. Let the chord ring",
            "ACCENT": "Muted eighths with an open, accented hit on 2 and 4",
            "PUSH": "Change chords on the & of 4, an eighth before the bar line",
            "STAB": "Short stabs on 2 and 4. Choke each one by relaxing the fretting hand"},
   "tutorial_query": "rock rhythm guitar eighth notes palm muting lesson",
   "default_bpm": 110, "min_bpm": 60, "max_bpm": 190, "default_sets": 3, "default_reps": 8}'::jsonb,
 200, 120),

('rhythm.rock_open_riffing', 'rhythm', 'Rock', 'Open-Chord Riffing',
 'The classic rock move of decorating open chords with sus notes and bass notes while the strum keeps going.',
 'random_chord_picker',
 '{"pool": ["A","D","E","G","C"], "default_selected": ["A","D","G"], "tempo_label": "Click tempo",
   "patterns": ["Hammer the sus4 on and off inside the strum",
                "Pick the bass note on 1, then strum the rest of the bar",
                "Walk the bass note up or down into the next chord on beat 4",
                "Big ringing hit on 1, then tight eighths on the top strings"],
   "tutorial_query": "classic rock rhythm guitar sus4 open chord riffs",
   "default_bpm": 90, "min_bpm": 50, "max_bpm": 160, "default_sets": 3, "default_reps": 8}'::jsonb,
 200, 130),

-- Rhythm Guitar: Metal
('rhythm.metal_thrash', 'rhythm', 'Metal', 'Thrash Downpicking & Gallops',
 'Tight, palm-muted riffing on the low string, the backbone of thrash. Downpicking builds endurance, gallops build drive.',
 'cue_picker',
 '{"pool": ["DOWN","GALLOP","REVERSE","16THS","CHROM"], "default_selected": ["DOWN","GALLOP","16THS"], "pool_label": "Patterns", "tempo_label": "Click tempo",
   "cues": {"DOWN": "Palm-muted eighths on the open low string, downstrokes only",
            "GALLOP": "An eighth and two sixteenths on every beat: DA-da-da",
            "REVERSE": "Reverse gallop, two sixteenths then an eighth: da-da-DA",
            "16THS": "Straight alternate-picked sixteenths, muted, locked to the click",
            "CHROM": "Muted downpicked eighths climbing 0-1-2-3 on the low string, then back down"},
   "tutorial_query": "thrash metal downpicking gallop rhythm guitar lesson",
   "default_bpm": 120, "min_bpm": 70, "max_bpm": 240, "default_sets": 3, "default_reps": 8}'::jsonb,
 220, 140),

('rhythm.metal_tremolo', 'rhythm', 'Metal', 'Tremolo Picking',
 'Fast, even alternate picking on one note or chord, the sound of death and black metal riffs. Relax the wrist and let the pick barely touch the string.',
 'cue_picker',
 '{"pool": ["NOTE","FIFTH","MINOR","SHIFT","BLAST"], "default_selected": ["NOTE","FIFTH","SHIFT"], "pool_label": "Drills", "tempo_label": "Click tempo",
   "cues": {"NOTE": "Tremolo one note in strict sixteenths, then move up a fret each bar",
            "FIFTH": "Tremolo a two-note power chord, keeping both strings even",
            "MINOR": "Black metal style: tremolo a full minor chord with small, fast strokes",
            "SHIFT": "Change notes on every beat without breaking the picking",
            "BLAST": "Sixteenths against a blast beat click, accenting every beat"},
   "tutorial_query": "tremolo picking tutorial death metal black metal",
   "default_bpm": 100, "min_bpm": 60, "max_bpm": 220, "default_sets": 3, "default_reps": 6}'::jsonb,
 220, 150),

('rhythm.metal_groove', 'rhythm', 'Metal', 'Groove & Djent Syncopation',
 'Syncopated chug patterns from groove metal and djent. Count the sixteenths out loud and let the accents fall across the bar line.',
 'cue_picker',
 '{"pool": ["3-3-2","5-5-6","OFFBEAT","PINCH","POLY"], "default_selected": ["3-3-2","OFFBEAT","PINCH"], "pool_label": "Rhythms", "tempo_label": "Click tempo",
   "cues": {"3-3-2": "Chug the first sixteenth of each group of 3, 3 and 2, twice a bar. Mute the rest",
            "5-5-6": "Chug the first sixteenth of each group of 5, 5 and 6. One cycle fills the bar",
            "OFFBEAT": "Chug on the e and a of every beat, with muted silence on the beat",
            "PINCH": "Chug eighths and squeal a pinch harmonic on the last note of the bar",
            "POLY": "Repeat a 5-sixteenth phrase over the click until it lands on 1 again, 5 bars later"},
   "tutorial_query": "djent groove metal syncopated rhythm guitar lesson",
   "default_bpm": 90, "min_bpm": 60, "max_bpm": 180, "default_sets": 3, "default_reps": 6}'::jsonb,
 220, 160),

-- Rhythm Guitar: Punk
('rhythm.punk_downstrokes', 'rhythm', 'Punk', 'Punk Downstrokes',
 'Fast, relentless downstroke eighths on power chords. Stamina and a loose wrist matter more than anything else here.',
 'cue_picker',
 '{"pool": ["MUTED","OPEN","CHANGE","ENDURE"], "default_selected": ["MUTED","OPEN","CHANGE","ENDURE"], "pool_label": "Drills", "tempo_label": "Click tempo",
   "cues": {"MUTED": "Palm-muted power chord eighths, downstrokes only",
            "OPEN": "Lift the mute and keep the same downstrokes ringing",
            "CHANGE": "Switch power chords every two beats without a gap",
            "ENDURE": "Four bars of nonstop downstrokes without slowing or tensing up"},
   "tutorial_query": "punk rock downstroke rhythm guitar lesson",
   "default_bpm": 140, "min_bpm": 80, "max_bpm": 240, "default_sets": 3, "default_reps": 8}'::jsonb,
 200, 170),

('rhythm.punk_dynamics', 'rhythm', 'Punk', 'Pop-Punk Dynamics',
 'Tight muted verses, big open choruses and octave riffs. The picking hand stays the same, only the muting and the voicing change.',
 'cue_picker',
 '{"pool": ["VERSE","CHORUS","BUILD","STOP","OCTAVE"], "default_selected": ["VERSE","CHORUS","STOP"], "pool_label": "Parts", "tempo_label": "Click tempo",
   "cues": {"VERSE": "Palm-muted eighths on one power chord, quiet and tight",
            "CHORUS": "Open, ringing eighths. Same picking hand, just lift the palm",
            "BUILD": "Start fully muted and lift the palm a little more each beat for one bar",
            "STOP": "Hit the chord on 1 and choke it. Silence on 2, 3 and 4",
            "OCTAVE": "Root on the A string, octave two frets up on the G string, D string muted. Eighths"},
   "tutorial_query": "pop punk rhythm guitar lesson palm muting octave chords",
   "default_bpm": 150, "min_bpm": 90, "max_bpm": 220, "default_sets": 3, "default_reps": 8}'::jsonb,
 200, 180),

-- Rhythm Guitar: Funk
('rhythm.funk_sixteenths', 'rhythm', 'Funk', 'Funk Sixteenth Scratch',
 'The wrist swings down and up on every sixteenth, all the time. The groove comes from choosing which strokes hit the chord and which stay muted.',
 'cue_picker',
 '{"pool": ["16THS","CHANK","ONE","2AND4","SYNC"], "default_selected": ["16THS","CHANK","2AND4"], "pool_label": "Patterns", "tempo_label": "Groove tempo",
   "cues": {"16THS": "Constant down-up sixteenths, all muted scratches. The wrist never stops",
            "CHANK": "A short chord stab on the & of every beat, released right away",
            "ONE": "Hit the chord hard on the one, then scratch the rest of the bar",
            "2AND4": "Scratches everywhere, with the full chord only on beats 2 and 4",
            "SYNC": "Chord on the a of beat 1 and the e of beat 3, scratches in between"},
   "tutorial_query": "funk rhythm guitar 16th note strumming lesson",
   "default_bpm": 90, "min_bpm": 60, "max_bpm": 130, "default_sets": 3, "default_reps": 8}'::jsonb,
 220, 190),

('rhythm.funk_chord_stabs', 'rhythm', 'Funk', 'Funk 9th Chord Stabs',
 'One movable 9th-chord grip, rooted on the A string, moved around the neck. Keep the stabs short and the scratches going between them.',
 'random_chord_picker',
 '{"pool": ["E9","A9","D9","G9","C9"], "default_selected": ["E9","A9","D9"], "tempo_label": "Groove tempo",
   "patterns": ["Stab on the & of each beat and release right away",
                "Slide into the chord from one fret below on the a of 4",
                "Scratch sixteenths, opening up on the chord for beats 2 and 4",
                "Two quick stabs, then two beats of scratching"],
   "tutorial_query": "funk guitar 9th chord stabs lesson",
   "default_bpm": 92, "min_bpm": 60, "max_bpm": 130, "default_sets": 3, "default_reps": 8}'::jsonb,
 220, 200),

-- Rhythm Guitar: Reggae & Ska
('rhythm.reggae_skank', 'rhythm', 'Reggae & Ska', 'Reggae Skank',
 'Short, choked chords on the offbeats while the bass and drums own the downbeats. Let the silence groove as much as the chops.',
 'random_chord_picker',
 '{"pool": ["Am","Dm","Em","C","G","F","D"], "default_selected": ["Am","Dm","Em"], "tempo_label": "Groove tempo",
   "patterns": ["Chop on beats 2 and 4 and choke it right away",
                "Double chop: two quick sixteenth stabs on 2 and 4",
                "Chops on the top three strings only, tiny and tight",
                "Release the fretting hand between chops so nothing rings"],
   "tutorial_query": "reggae skank rhythm guitar lesson",
   "default_bpm": 76, "min_bpm": 50, "max_bpm": 110, "default_sets": 3, "default_reps": 8}'::jsonb,
 200, 210),

('rhythm.ska_upstrokes', 'rhythm', 'Reggae & Ska', 'Ska Upstrokes',
 'Bright upstroke chops on every offbeat at a much faster tempo than reggae. Keep them short and even from the first bar to the last.',
 'random_chord_picker',
 '{"pool": ["C","G","D","A","E","F","Am","Em"], "default_selected": ["C","G","D"], "tempo_label": "Click tempo",
   "patterns": ["Upstroke chop on every &, muted on the beat",
                "Upstrokes on every & with a muted downstroke scratch on the beat",
                "Accent the & of 2 and 4 harder than the others",
                "Change chords every two beats without losing an upstroke"],
   "tutorial_query": "ska upstroke rhythm guitar lesson",
   "default_bpm": 130, "min_bpm": 80, "max_bpm": 220, "default_sets": 3, "default_reps": 8}'::jsonb,
 200, 220),

-- Lead Guitar: Blues
('lead.blues_bends', 'lead', 'Blues', 'Blues Bends & Vibrato',
 'Bends that land in tune and vibrato with a steady pulse are most of the blues sound. Check each bend against the target note fretted normally.',
 'cue_picker',
 '{"pool": ["WHOLE","CURL","PRE","RELEASE","UNISON","VIBRATO"], "default_selected": ["WHOLE","CURL","VIBRATO"], "pool_label": "Techniques", "tempo_label": "Click tempo",
   "cues": {"WHOLE": "Bend a whole step on the G string and hold it in tune for 2 beats",
            "CURL": "A quarter-step curl on the minor 3rd, the blues smear",
            "PRE": "Pre-bend silently, pick, then release down to the fretted note",
            "RELEASE": "Bend up, pick again at the top, then release slowly on beat 3",
            "UNISON": "Bend the G string up to match the note on the B string, both ringing",
            "VIBRATO": "Wide, even vibrato on the B string, locked to eighth notes"},
   "tutorial_query": "blues guitar bending and vibrato lesson",
   "default_bpm": 70, "min_bpm": 40, "max_bpm": 120, "default_sets": 3, "default_reps": 6}'::jsonb,
 220, 100),

('lead.blues_phrasing', 'lead', 'Blues', 'Blues Phrasing',
 'Call and response, space and repetition. Short phrases from the minor pentatonic and blues scale, played over a 12-bar.',
 'cue_picker',
 '{"pool": ["CALL","ANSWER","REPEAT","BLUE","TARGET","SPACE"], "default_selected": ["CALL","ANSWER","REPEAT"], "pool_label": "Ideas", "tempo_label": "Click tempo",
   "cues": {"CALL": "Play a 2-bar phrase, then leave 2 bars of silence",
            "ANSWER": "Answer your last phrase with a shorter one that ends on the root",
            "REPEAT": "One short lick three times, changing only the last note",
            "BLUE": "Pass through the flat 5 blue note on the way down the scale",
            "TARGET": "Land on a note of the new chord right when the change hits",
            "SPACE": "Only four notes per bar. Make each one count"},
   "tutorial_query": "blues guitar phrasing call and response lesson",
   "default_bpm": 72, "min_bpm": 50, "max_bpm": 140, "default_sets": 3, "default_reps": 6}'::jsonb,
 200, 110),

-- Lead Guitar: Rock
('lead.rock_licks', 'lead', 'Rock', 'Rock Lick Toolkit',
 'The moves behind classic rock solos, all from the pentatonic box you already know: repeating licks, double stops, fast runs and slides.',
 'cue_picker',
 '{"pool": ["REPEAT","DOUBLE","RUN","SLIDE"], "default_selected": ["REPEAT","DOUBLE","RUN","SLIDE"], "pool_label": "Licks", "tempo_label": "Click tempo",
   "cues": {"REPEAT": "Loop a 3-note pull-off lick on the top two strings in triplets",
            "DOUBLE": "Double stops: two neighbouring strings at the same fret, picked together",
            "RUN": "Descend box 1 in groups of six notes, one group per beat",
            "SLIDE": "Slide into box 1 from two frets below and land on the root"},
   "tutorial_query": "classic rock guitar licks pentatonic lesson",
   "default_bpm": 90, "min_bpm": 50, "max_bpm": 180, "default_sets": 3, "default_reps": 6}'::jsonb,
 220, 120),

('lead.rock_legato', 'lead', 'Rock', 'Legato Hammer-Ons & Pull-Offs',
 'Smooth, flowing lines with one pick per string. Hammer-ons and pull-offs should be as loud as the picked notes.',
 'cue_picker',
 '{"pool": ["HAMMER","PULL","ROLL","ASCEND","DESCEND"], "default_selected": ["HAMMER","PULL","ROLL"], "pool_label": "Drills", "tempo_label": "Click tempo",
   "cues": {"HAMMER": "Pick once, then hammer the next two notes on the same string at an even volume",
            "PULL": "Pull-offs down one string, flicking the finger slightly off the string",
            "ROLL": "Hammer and pull between two frets for a full bar, as evenly as you can",
            "ASCEND": "Pick only the first note on each string going up the pentatonic box",
            "DESCEND": "Pick only the first note on each string coming down the box"},
   "tutorial_query": "legato guitar hammer ons pull offs lesson",
   "default_bpm": 70, "min_bpm": 40, "max_bpm": 160, "default_sets": 3, "default_reps": 6}'::jsonb,
 220, 130),

-- Lead Guitar: Metal
('lead.metal_shred', 'lead', 'Metal', 'Shred Alternate Picking',
 'Metal lead speed built from short, clean bursts. Stay relaxed, and slow the click down the moment notes start to smear.',
 'cue_picker',
 '{"pool": ["BURST","SIXES","3NPS","CROSS"], "default_selected": ["BURST","SIXES","3NPS"], "pool_label": "Drills", "tempo_label": "Click tempo",
   "cues": {"BURST": "Four notes as fast as you can play them cleanly, then a full beat of rest",
            "SIXES": "Six-note groups descending through the scale, alternate picked",
            "3NPS": "Three notes per string up the natural minor scale, strict alternate picking",
            "CROSS": "Two notes per string across all six strings and back, never missing a stroke"},
   "tutorial_query": "metal shred alternate picking exercises",
   "default_bpm": 80, "min_bpm": 50, "max_bpm": 200, "default_sets": 3, "default_reps": 6}'::jsonb,
 250, 140),

('lead.metal_sweeps_tapping', 'lead', 'Metal', 'Sweeps & Tapping',
 'Arpeggio sweeps and two-hand tapping, the flashiest tools in metal lead. Accuracy first: each note should sound on its own.',
 'cue_picker',
 '{"pool": ["SWEEP3","SWEEP5","TAP","MOVE"], "default_selected": ["SWEEP3","TAP"], "pool_label": "Drills", "tempo_label": "Click tempo",
   "cues": {"SWEEP3": "Three-string minor arpeggio sweep, one note per string, no notes ringing together",
            "SWEEP5": "Five-string minor arpeggio sweep up and back down, muting as you go",
            "TAP": "Tap, pull off to your index, hammer with your ring finger. Repeat in triplets",
            "MOVE": "Keep the tapping triplets going and move the tapped note to follow a chord change"},
   "tutorial_query": "sweep picking and tapping lesson for beginners metal",
   "default_bpm": 60, "min_bpm": 40, "max_bpm": 160, "default_sets": 3, "default_reps": 6}'::jsonb,
 250, 150),

-- Lead Guitar: Country
('lead.country_chicken_picking', 'lead', 'Country', 'Chicken Picking',
 'Hybrid picking with the pick and the middle and ring fingers, the snappy core of country lead guitar.',
 'cue_picker',
 '{"pool": ["HYBRID","SNAP","CLUCK","ROLL"], "default_selected": ["HYBRID","SNAP","CLUCK"], "pool_label": "Techniques", "tempo_label": "Click tempo",
   "cues": {"HYBRID": "Pick the low note, pluck the higher string with your middle finger, alternating evenly",
            "SNAP": "Pluck with the middle finger hard enough to snap the string against the frets",
            "CLUCK": "Mute the string with the fretting hand and pick it for a percussive cluck before each note",
            "ROLL": "Banjo roll across three strings: pick, middle, ring, repeating"},
   "tutorial_query": "country chicken picking hybrid picking lesson",
   "default_bpm": 80, "min_bpm": 50, "max_bpm": 180, "default_sets": 3, "default_reps": 6}'::jsonb,
 220, 160),

('lead.country_steel_bends', 'lead', 'Country', 'Steel Bends & Double Stops',
 'Country lead leans on the major pentatonic, pedal-steel bends and sweet double stops. Keep every bend in tune against the held note.',
 'cue_picker',
 '{"pool": ["STEEL","3RDS","6THS","MAJOR"], "default_selected": ["STEEL","3RDS","6THS","MAJOR"], "pool_label": "Techniques", "tempo_label": "Click tempo",
   "cues": {"STEEL": "Bend the G string a whole step while holding a note on the B string, pedal steel style",
            "3RDS": "Double stops in 3rds on the G and B strings, walking up the major scale",
            "6THS": "Double stops in 6ths on the G and high E strings, sliding up the neck",
            "MAJOR": "Major pentatonic up and down. It is the minor box, three frets lower"},
   "tutorial_query": "country guitar double stops pedal steel bends lesson",
   "default_bpm": 70, "min_bpm": 40, "max_bpm": 140, "default_sets": 3, "default_reps": 6}'::jsonb,
 220, 170),

-- Lead Guitar: Jazz
('lead.jazz_arpeggios', 'lead', 'Jazz', 'Chord-Tone Arpeggios',
 'Jazz lines outline the changes. Name each chord tone as you play it, and land on the 3rd or 7th when the chord changes.',
 'random_chord_picker',
 '{"pool": ["Dm7","G7","Cmaj7","Am7","D7","Gmaj7","E7","A7"], "default_selected": ["Dm7","G7","Cmaj7"], "tempo_label": "Click tempo",
   "patterns": ["Arpeggiate up from the root: 1, 3, 5, 7",
                "Arpeggiate down from the 7th to the root",
                "Start on the 3rd: 3, 5, 7, 9",
                "Approach the 3rd from a half step below, then play the arpeggio"],
   "tutorial_query": "jazz guitar arpeggios ii V I lesson",
   "default_bpm": 80, "min_bpm": 50, "max_bpm": 200, "default_sets": 3, "default_reps": 8}'::jsonb,
 250, 180),

('lead.jazz_enclosures', 'lead', 'Jazz', 'Approach Notes & Enclosures',
 'The chromatic glue of bebop. Every idea here aims at a chord tone and lands on it on the beat.',
 'cue_picker',
 '{"pool": ["BELOW","ABOVE","ENCLOSE","PASSING","BEBOP"], "default_selected": ["BELOW","ABOVE","ENCLOSE"], "pool_label": "Ideas", "tempo_label": "Click tempo",
   "cues": {"BELOW": "Approach each chord tone from a half step below",
            "ABOVE": "Approach each chord tone from one scale step above",
            "ENCLOSE": "Enclose the target: one note above, one below, then land on it",
            "PASSING": "Put a chromatic passing note between two scale notes, on the &",
            "BEBOP": "Descend the bebop dominant scale: mixolydian with an added major 7th"},
   "tutorial_query": "jazz guitar enclosures approach notes lesson",
   "default_bpm": 90, "min_bpm": 50, "max_bpm": 220, "default_sets": 3, "default_reps": 6}'::jsonb,
 250, 190),

-- Bass Guitar: Blues
('bass.blues_shuffle', 'bass', 'Blues', 'Blues Shuffle Bass',
 'The walking boogie under a 12-bar blues. Swing it long-short and let the 6th and b7 do the talking.',
 'cue_picker',
 '{"pool": ["E","A","B","D","G","C"], "default_selected": ["E","A","B"], "pool_label": "Roots", "tempo_label": "Shuffle tempo",
   "patterns": ["Boogie line in swung eighths: 1, 3, 5, 6, b7, 6, 5, 3",
                "Root and octave shuffle, long-short",
                "1, 5, 6, 5 shuffle, repeating",
                "Two bars on this root, then walk into the next chord"],
   "tutorial_query": "blues shuffle bass line lesson",
   "default_bpm": 80, "min_bpm": 50, "max_bpm": 160, "default_sets": 3, "default_reps": 8}'::jsonb,
 200, 100),

('bass.blues_twelve_bar', 'bass', 'Blues', '12-Bar Blues Changes',
 'Hold down the form so the band can lean on you. Play each version once through, counting bars out loud.',
 'cue_picker',
 '{"pool": ["SLOW","QUICK","STOP","MINOR","TURN"], "default_selected": ["SLOW","QUICK"], "pool_label": "Forms", "tempo_label": "Click tempo",
   "cues": {"SLOW": "I I I I · IV IV I I · V IV I V. Walk into every change",
            "QUICK": "I IV I I · IV IV I I · V IV I V. The quick change comes in bar 2",
            "STOP": "Stop-time: root on beat 1 of bars 1 to 4, then groove bars 5 to 12",
            "MINOR": "i i i i · iv iv i i · bVI V i V",
            "TURN": "Bars 11 and 12 only: I to V with a chromatic walk up, four times through"},
   "tutorial_query": "12 bar blues bass line lesson",
   "default_bpm": 80, "min_bpm": 50, "max_bpm": 150, "default_sets": 3, "default_reps": 4}'::jsonb,
 120, 110),

-- Bass Guitar: Rock
('bass.rock_eighths', 'bass', 'Rock', 'Rock Eighth Notes',
 'The rock bass job: relentless, even eighths that glue the kick drum to the guitars. Every note the same length and volume.',
 'cue_picker',
 '{"pool": ["E","A","D","G","C","B"], "default_selected": ["E","A","D","G"], "pool_label": "Roots", "tempo_label": "Click tempo",
   "patterns": ["Steady eighths on the root, locked to the kick",
                "Root eighths with an octave jump on beat 4",
                "Root eighths with a passing note into the next chord on the & of 4",
                "Palm-muted eighths with a pick, all downstrokes"],
   "tutorial_query": "rock bass eighth notes lesson",
   "default_bpm": 110, "min_bpm": 60, "max_bpm": 190, "default_sets": 3, "default_reps": 8}'::jsonb,
 200, 120),

('bass.rock_octaves_fills', 'bass', 'Rock', 'Octaves & Fills',
 'Break up the root notes with octave jumps and short fills that lead into the next chord.',
 'cue_picker',
 '{"pool": ["E","A","D","G","C","B"], "default_selected": ["E","A","D","G"], "pool_label": "Roots", "tempo_label": "Click tempo",
   "patterns": ["Root, octave, root, octave in eighths",
                "Root for 3 beats, then a 4-note fill up to the next root",
                "Root, 5th, octave, 5th in eighths",
                "Slide from the root up to the octave on beat 4"],
   "tutorial_query": "rock bass octaves and fills lesson",
   "default_bpm": 100, "min_bpm": 60, "max_bpm": 180, "default_sets": 3, "default_reps": 8}'::jsonb,
 200, 130),

-- Bass Guitar: Metal
('bass.metal_gallops', 'bass', 'Metal', 'Gallops & Pedal Tones',
 'Metal bass doubles the guitar riff and locks to the kick drum. Keep notes short and muted so the low end stays tight at speed.',
 'cue_picker',
 '{"pool": ["GALLOP","REVERSE","16THS","PEDAL","CHUG"], "default_selected": ["GALLOP","16THS","PEDAL"], "pool_label": "Patterns", "tempo_label": "Click tempo",
   "cues": {"GALLOP": "Gallop with the guitars: an eighth and two sixteenths, DA-da-da",
            "REVERSE": "Reverse gallop, two sixteenths then an eighth: da-da-DA",
            "16THS": "Straight sixteenths with a pick or two fingers, following the double kick",
            "PEDAL": "Pedal the open low string between fretted notes: 0-3-0-5-0-6-0-5",
            "CHUG": "Match a guitar chug: short, muted notes with dead silence between them"},
   "tutorial_query": "metal bass gallop picking lesson",
   "default_bpm": 120, "min_bpm": 70, "max_bpm": 220, "default_sets": 3, "default_reps": 8}'::jsonb,
 220, 140),

('bass.metal_speed', 'bass', 'Metal', 'Speed & Endurance',
 'Death and thrash tempos need sixteenths that stay even for whole songs. Pick or alternate two fingers, and build up in short bursts.',
 'cue_picker',
 '{"pool": ["BURST","ENDURE","STRING","MUTE"], "default_selected": ["BURST","ENDURE","MUTE"], "pool_label": "Drills", "tempo_label": "Click tempo",
   "cues": {"BURST": "One beat of fast sixteenths, then one beat of rest",
            "ENDURE": "Four bars of nonstop sixteenths without tensing up",
            "STRING": "Sixteenths that cross between two strings on every beat",
            "MUTE": "Sixteenths with both hands muting every string you are not playing"},
   "tutorial_query": "fast bass picking endurance metal exercises",
   "default_bpm": 100, "min_bpm": 60, "max_bpm": 220, "default_sets": 3, "default_reps": 6}'::jsonb,
 220, 150),

-- Bass Guitar: Punk
('bass.punk_downpicking', 'bass', 'Punk', 'Punk Downpicking',
 'Fast, downpicked eighths that never let up. Stamina first, then speed.',
 'cue_picker',
 '{"pool": ["E","A","D","G","B","C"], "default_selected": ["E","A","D","G"], "pool_label": "Roots", "tempo_label": "Click tempo",
   "patterns": ["Downpicked eighths on the root, no breaks",
                "Follow the guitar power chords root for root",
                "Eighths on the root, then walk up the scale into the next chord",
                "Four bars of downpicking without slowing or tensing up"],
   "tutorial_query": "punk bass downpicking lesson",
   "default_bpm": 150, "min_bpm": 90, "max_bpm": 240, "default_sets": 3, "default_reps": 8}'::jsonb,
 200, 160),

('bass.punk_runs', 'bass', 'Punk', 'Pop-Punk Runs',
 'Pop-punk bass plays melodic runs between the chords instead of sitting on the root. Keep the eighths driving underneath.',
 'cue_picker',
 '{"pool": ["E","A","D","G","B","C"], "default_selected": ["E","A","D","G"], "pool_label": "Roots", "tempo_label": "Click tempo",
   "patterns": ["Walk up the major scale from the root to the next chord in eighths",
                "Root for 2 beats, then a 4-note run to the next root",
                "Play the 3rd and 5th under the chord for a bar instead of the root",
                "Run down from the octave to the root"],
   "tutorial_query": "pop punk bass lines lesson",
   "default_bpm": 160, "min_bpm": 90, "max_bpm": 230, "default_sets": 3, "default_reps": 8}'::jsonb,
 200, 170),

-- Bass Guitar: Funk
('bass.funk_slap', 'bass', 'Funk', 'Slap & Pop',
 'The percussive thumb-and-pop technique of funk bass. Aim for the same volume from the thumb and the pop.',
 'cue_picker',
 '{"pool": ["THUMB","POP","OCTAVE","GHOST","HAMMER"], "default_selected": ["THUMB","POP","OCTAVE"], "pool_label": "Techniques", "tempo_label": "Groove tempo",
   "cues": {"THUMB": "Thumb slap on the root, bouncing off the string near the neck, quarter notes",
            "POP": "Pop a string with your index finger: pull it up and let it snap back",
            "OCTAVE": "Thumb the root, pop the octave, repeating in eighths",
            "GHOST": "Slap, ghost, pop, ghost in sixteenths, muting with the fretting hand",
            "HAMMER": "Slap an open string, then hammer on the next note without plucking"},
   "tutorial_query": "slap bass for beginners lesson",
   "default_bpm": 80, "min_bpm": 50, "max_bpm": 130, "default_sets": 3, "default_reps": 8}'::jsonb,
 220, 180),

('bass.funk_fingerstyle', 'bass', 'Funk', 'Fingerstyle Funk Grooves',
 'Sixteenth-note funk with the fingers: a big one, muted ghost notes, and syncopation that leaves room for the drums.',
 'cue_picker',
 '{"pool": ["E","A","D","G","C"], "default_selected": ["E","A","D"], "pool_label": "Roots", "tempo_label": "Groove tempo",
   "patterns": ["Hit the one hard, then fill the bar with muted sixteenth ghost notes",
                "Root, b7, octave in sixteenths, landing back on the one",
                "Leave beat 3 empty and hit the & of 3",
                "Root on the one and the & of 2, ghost notes everywhere else"],
   "tutorial_query": "funk bass 16th note groove ghost notes lesson",
   "default_bpm": 90, "min_bpm": 60, "max_bpm": 130, "default_sets": 3, "default_reps": 8}'::jsonb,
 220, 190),

-- Bass Guitar: Reggae & Ska
('bass.reggae_one_drop', 'bass', 'Reggae & Ska', 'One Drop Bass',
 'Deep, round reggae bass that leaves space. Pluck near the neck and let the rests groove as much as the notes.',
 'cue_picker',
 '{"pool": ["A","D","E","G","C","F"], "default_selected": ["A","D","E"], "pool_label": "Roots", "tempo_label": "Groove tempo",
   "patterns": ["Rest on beat 1, then land the root with the kick on beat 3",
                "Root, then walk down the minor pentatonic to the 5th",
                "Let the root ring long and leave the next beat empty",
                "Root and octave, short and round, with space between"],
   "tutorial_query": "reggae bass one drop lesson",
   "default_bpm": 72, "min_bpm": 50, "max_bpm": 110, "default_sets": 3, "default_reps": 8}'::jsonb,
 200, 200),

('bass.ska_walking', 'bass', 'Reggae & Ska', 'Ska Walking Bass',
 'Fast walking lines under the upstroke guitars. Quarter notes that keep moving and point at the next chord.',
 'cue_picker',
 '{"pool": ["C","G","D","A","E","F"], "default_selected": ["C","G","D"], "pool_label": "Roots", "tempo_label": "Click tempo",
   "patterns": ["Walk quarter notes up the major scale into the next chord",
                "Root and 5th walking in quarter notes",
                "A chromatic approach note into each new root",
                "Octave jump on beat 4, then walk into the next bar"],
   "tutorial_query": "ska bass walking line lesson",
   "default_bpm": 140, "min_bpm": 90, "max_bpm": 220, "default_sets": 3, "default_reps": 8}'::jsonb,
 200, 210);
