-- Clean vocals path, laid out like Extreme Vocals: foundations, core
-- techniques, then genre styles (rock, pop, R&B and soul, folk and country,
-- metal cleans) and application. These use cue_picker: the big label is a
-- vowel, word or cue, and the detail line comes from `cues` (per item) or
-- `patterns` (random). Every skill has a tutorial_query.

INSERT INTO skills (id, path, category, name, description, generator_type, config, mastery_reps, sort_order) VALUES

-- Foundations
('clean_vocals.breathing', 'clean_vocals', 'Foundations', 'Breathing & Support',
 'Steady air is what keeps a note in tune and a phrase from running out. Breathe low, keep the ribs open, and let the belly do the work.',
 'cue_picker',
 '{"pool": ["LOW","SSS","HA","4-8","PHRASE"], "default_selected": ["LOW","SSS","HA"], "pool_label": "Exercises", "tempo_label": "Cue tempo",
   "cues": {"LOW": "Hand on the belly: it moves out on the inhale while the shoulders stay still",
            "SSS": "One slow, even hiss on a single breath. Keep the ribs open as long as you can",
            "HA": "Staccato HA on one comfortable note, one per beat, belly bouncing each time",
            "4-8": "Inhale for 4 beats, then sing one soft note for 8",
            "PHRASE": "Sing a long phrase on one breath and count how many beats you last"},
   "tutorial_query": "breath support for singing beginners",
   "default_bpm": 60, "min_bpm": 40, "max_bpm": 120, "default_sets": 3, "default_reps": 6}'::jsonb,
 120, 10),

('clean_vocals.warmups', 'clean_vocals', 'Foundations', 'Warm-ups',
 'Five minutes of gentle, semi-occluded exercises before you sing. They get the cords moving without any strain.',
 'cue_picker',
 '{"pool": ["TRILL","SIREN","HUM","STRAW","NG"], "default_selected": ["TRILL","SIREN","HUM","STRAW","NG"], "pool_label": "Exercises", "tempo_label": "Cue tempo",
   "cues": {"TRILL": "Lip trill on a 5-note scale, up and back down",
            "SIREN": "Slide on OO from your lowest note to your highest and back",
            "HUM": "Hum a 5-note scale, lips closed and teeth apart. Feel the buzz",
            "STRAW": "Sing a simple tune through a straw",
            "NG": "NG slides, like the end of the word sing, through your whole range"},
   "tutorial_query": "vocal warm up for singers",
   "default_bpm": 50, "min_bpm": 30, "max_bpm": 100, "default_sets": 2, "default_reps": 5}'::jsonb,
 100, 20),

('clean_vocals.pitch_matching', 'clean_vocals', 'Foundations', 'Pitch Matching',
 'Hear a note, then sing it right in the middle. Pick any octave that sits comfortably in your voice.',
 'cue_picker',
 '{"pool": ["C","D","E","F","G","A","B","C#","Eb","F#","Ab","Bb"], "default_selected": ["C","D","E","F","G","A","B"], "pool_label": "Notes", "tempo_label": "Cue tempo",
   "patterns": ["Play the note on an instrument, then sing it on AH for 4 beats",
                "Sing it first, then check it against a piano, a guitar or the chromatic tuner",
                "Slide up to the note from below and stop right on it",
                "Sing the note, then hum it without losing the pitch"],
   "tutorial_query": "how to sing in tune pitch matching exercises",
   "default_bpm": 40, "min_bpm": 20, "max_bpm": 90, "default_sets": 3, "default_reps": 8}'::jsonb,
 200, 30),

-- Core techniques
('clean_vocals.scales', 'clean_vocals', 'Core Techniques', 'Scales & Intervals',
 'The patterns every voice teacher uses. Keep each note clean and connected, then move the pattern up a half step.',
 'cue_picker',
 '{"pool": ["5-NOTE","ARPEG","OCTAVE","3RDS"], "default_selected": ["5-NOTE","ARPEG","OCTAVE","3RDS"], "pool_label": "Patterns", "tempo_label": "Cue tempo",
   "cues": {"5-NOTE": "1 2 3 4 5 4 3 2 1 on AH, then move up a half step",
            "ARPEG": "1 3 5 8 5 3 1 on EE, smooth and connected",
            "OCTAVE": "Jump from 1 to 8 and back without scooping into the top note",
            "3RDS": "Scale in thirds: 1 3 2 4 3 5 4 2 1"},
   "tutorial_query": "vocal scales and intervals exercises for singers",
   "default_bpm": 70, "min_bpm": 40, "max_bpm": 140, "default_sets": 3, "default_reps": 6}'::jsonb,
 200, 40),

('clean_vocals.registers', 'clean_vocals', 'Core Techniques', 'Chest, Head & Mix',
 'Every voice has a break between chest and head voice. Find where yours is, then smooth it over with a mixed voice.',
 'cue_picker',
 '{"pool": ["CHEST","HEAD","MIX","BRIDGE","FLIP"], "default_selected": ["CHEST","HEAD","MIX"], "pool_label": "Registers", "tempo_label": "Cue tempo",
   "cues": {"CHEST": "Speech-like AH in your lower range, full but not pushed",
            "HEAD": "Light OO in your upper range, like a gentle hoot",
            "MIX": "Bratty NAY on a 5-note scale through the break, keeping it light",
            "BRIDGE": "Slide on GEE across your break without the voice cracking",
            "FLIP": "Yodel on purpose: flip between chest and head on two notes to find the break"},
   "tutorial_query": "chest voice head voice mixed voice exercises",
   "default_bpm": 60, "min_bpm": 40, "max_bpm": 120, "default_sets": 3, "default_reps": 6}'::jsonb,
 220, 50),

('clean_vocals.belting', 'clean_vocals', 'Core Techniques', 'Belting',
 'The powerful, speech-like sound of rock, pop and musical theatre. Loud and bright, carried by breath and never pushed from the throat.',
 'cue_picker',
 '{"pool": ["HEY","YEAH","NAY","OH"], "default_selected": ["HEY","YEAH","NAY"], "pool_label": "Words", "tempo_label": "Cue tempo",
   "patterns": ["Call it out like shouting to a friend across the street, on a comfortable note",
                "Belt for 2 beats, then drop back to speaking volume",
                "Belt a short phrase that climbs 3 notes, keeping the vowel open",
                "Stop the moment it feels tight. Belting should feel loud, not strained"],
   "tutorial_query": "how to belt safely singing tutorial",
   "default_bpm": 60, "min_bpm": 40, "max_bpm": 120, "default_sets": 3, "default_reps": 6}'::jsonb,
 200, 60),

('clean_vocals.vibrato', 'clean_vocals', 'Core Techniques', 'Vibrato',
 'A relaxed, even wobble in pitch that comes from freedom, not force. Start from a straight tone and let it bloom.',
 'cue_picker',
 '{"pool": ["AH","OH","EE","OO"], "default_selected": ["AH","OH","EE"], "pool_label": "Vowels", "tempo_label": "Cue tempo",
   "patterns": ["Hold a straight tone for 2 beats, then let it relax into vibrato",
                "Wobble slowly between the note and a half step above, then speed up",
                "Vibrato only on the last note of a phrase",
                "Keep the vibrato even in speed and width for 4 beats"],
   "tutorial_query": "how to sing with vibrato exercises",
   "default_bpm": 60, "min_bpm": 40, "max_bpm": 120, "default_sets": 3, "default_reps": 6}'::jsonb,
 200, 70),

-- Styles
('clean_vocals.rock', 'clean_vocals', 'Styles', 'Rock Vocals',
 'Bright, open vowels, belted choruses and a little edge at the peaks. Power comes from air and placement, not volume from the throat.',
 'cue_picker',
 '{"pool": ["HEY","YEAH","WHOA","OH","NO"], "default_selected": ["HEY","YEAH","WHOA"], "pool_label": "Words", "tempo_label": "Cue tempo",
   "patterns": ["Belt it on a bright, open vowel on a comfortable high note",
                "Add a short cry or break at the end of the note",
                "Start clean and add a touch of edge only at the peak",
                "Hold it and finish with a wide vibrato"],
   "tutorial_query": "rock singing technique tutorial",
   "default_bpm": 90, "min_bpm": 50, "max_bpm": 180, "default_sets": 3, "default_reps": 6}'::jsonb,
 200, 80),

('clean_vocals.pop', 'clean_vocals', 'Styles', 'Pop Vocals',
 'Close, conversational phrasing with breathy verses, clear choruses and small runs. The rhythm of the words matters as much as the notes.',
 'cue_picker',
 '{"pool": ["OOH","YEAH","OH","AH"], "default_selected": ["OOH","YEAH","OH"], "pool_label": "Words", "tempo_label": "Cue tempo",
   "patterns": ["Breathy verse tone, then a clear chorus tone on the same note",
                "A short 3-note run on the vowel, slow and then faster",
                "Flip into a soft falsetto at the end of the note",
                "Sing it on the beat, then sit slightly behind it"],
   "tutorial_query": "pop singing technique tutorial",
   "default_bpm": 96, "min_bpm": 60, "max_bpm": 160, "default_sets": 3, "default_reps": 6}'::jsonb,
 200, 90),

('clean_vocals.rnb_soul', 'clean_vocals', 'Styles', 'R&B & Soul',
 'Runs, melisma and bluesy slides. Learn each run slowly, note by note, before letting it fly.',
 'cue_picker',
 '{"pool": ["OH","YEAH","OOH","BABY"], "default_selected": ["OH","YEAH","OOH"], "pool_label": "Words", "tempo_label": "Cue tempo",
   "patterns": ["A 5-note descending pentatonic run on the vowel",
                "Melisma: stretch one syllable over 4 notes",
                "Grace note: flick up to the note from a step below",
                "Slide into the note and add vibrato at the end"],
   "tutorial_query": "r&b vocal runs tutorial for beginners",
   "default_bpm": 80, "min_bpm": 50, "max_bpm": 140, "default_sets": 3, "default_reps": 6}'::jsonb,
 220, 100),

('clean_vocals.folk_country', 'clean_vocals', 'Styles', 'Folk & Country',
 'Plain, honest storytelling with a bit of twang and the odd flip into head voice. The words come first.',
 'cue_picker',
 '{"pool": ["AY","OH","EE","HOME"], "default_selected": ["AY","OH","HOME"], "pool_label": "Words", "tempo_label": "Cue tempo",
   "patterns": ["Add twang: a slightly nasal, bright AY sound",
                "Country flip: break into head voice for a moment at the end of the note",
                "Sing it plainly, as if you were speaking, with no vibrato",
                "Slide down off the end of the note"],
   "tutorial_query": "country singing twang tutorial",
   "default_bpm": 80, "min_bpm": 50, "max_bpm": 140, "default_sets": 3, "default_reps": 6}'::jsonb,
 200, 110),

('clean_vocals.metal_cleans', 'clean_vocals', 'Styles', 'Metal Cleans',
 'Soaring, sustained clean vocals that cut through loud guitars, from power metal to metalcore choruses. Pairs with the Extreme Vocals path.',
 'cue_picker',
 '{"pool": ["AH","OH","EH","AY"], "default_selected": ["AH","OH","EH"], "pool_label": "Vowels", "tempo_label": "Cue tempo",
   "patterns": ["Soar on a sustained high note with a steady, wide vibrato",
                "Power metal: a bright, ringing tone on an open vowel",
                "Metalcore chorus: a clean belt with a clear, forward tone",
                "Go from a speaking voice straight into a full clean belt with no break"],
   "tutorial_query": "metal clean singing technique tutorial",
   "default_bpm": 90, "min_bpm": 50, "max_bpm": 200, "default_sets": 3, "default_reps": 6}'::jsonb,
 220, 120),

-- Application
('clean_vocals.phrasing', 'clean_vocals', 'Application', 'Rhythmic Phrasing',
 'Put the words on the grid. Sing any lyric line you know in each rhythm against the click.',
 'cue_picker',
 '{"pool": ["1/4","1/8","TRIP","SYNC","HOLD"], "default_selected": ["1/4","1/8","SYNC"], "pool_label": "Rhythms", "tempo_label": "Click tempo",
   "cues": {"1/4": "One syllable on every beat",
            "1/8": "Two syllables per beat",
            "TRIP": "Three syllables per beat",
            "SYNC": "Land the syllables on the & of each beat",
            "HOLD": "Sing a 4-beat note and cut it off exactly on the next beat"},
   "tutorial_query": "singing rhythm and phrasing exercises",
   "default_bpm": 90, "min_bpm": 60, "max_bpm": 180, "default_sets": 3, "default_reps": 8}'::jsonb,
 200, 130);
